### PR TITLE
feature/action deploy

### PR DESCRIPTION
**Pull request by duncanhealy**
action to deploy to docker registries on dockerhub and github

## Description
- remove platforms from docker hub - was erroring in the action,
- update the build context to 20.04 rather than latest
- add a cache layer
- switch to use lirantal dockerhub account

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated the documentation (if required).
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I added a picture of a cute animal cause it's fun

### CODE REVIEW

**Comment by duncanhealy** [comment]
@lirantal it seems to be just failing on the user password now

**Comment by lirantal** [comment]
@duncanhealy looking into it now

**Comment by lirantal** [comment]
As the PR doesn't have access to the secrets, I'll merge and let's see how it goes.

**Comment by lirantal** [comment]
@duncanhealy, error from GH Action:
image

**Comment by duncanhealy** [comment]
pity cannot go gh pr reopen as already merged
- the error is for the upper case OWASP-> owasp I'll open another pr
- see a warning for this https://docs.docker.com/engine/reference/commandline/login/#credentials-store in the logs maybe a docker logout after image pushed?

**Comment by lirantal** [comment]
Yep, had to merge it to be able to read secrets from the repo. Let's see now.

**Comment by lirantal** [comment]
Looks like we're good now @duncanhealy https://hub.docker.com/repository/docker/lirantal/cwe-tool 🚀 

FYI the following warnings if you wanted to clean things up too in a follow-up PR:
image

**Comment by duncanhealy** [comment]
it also pushed to the edge label on docker hub and we should add login details for the github package registry or switch to githubs container registry (which doesn't need a login)

**Comment by duncanhealy** [comment]
@lirantal - did you see this -> https://github.blog/changelog/2020-12-15-github-actions-environments-environment-protection-rules-and-environment-secrets-beta/

**Comment by lirantal** [comment]
Oh I haven't, that's interesting. So it means it allows specifically a person to access the secrets in that environment?

**Comment by duncanhealy** [comment]
Deployment is paused for pr until one of the approved `deployers` authorise it. Should fix the issue we had were you had to merge the pr, approval should give access to the secrets

**Comment by duncanhealy** [comment]
@lirantal  need to do a push on master to trigger semantic-version
or change the deploy.yml code to just do an on: release
as the latest and version tags not coming through on dockerhub, 
the version could be saved and git commited to package.json via https://github.com/semantic-release/git ?
we want the semantic-release to run in sequence before the docker build

**Comment by lirantal** [comment]
Let me see about setting it up for that `on: release` option: https://github.com/OWASP/cwe-tool/pull/15

**Comment by lirantal** [comment]
@duncanhealy deploying correctly but version tag is ambiguous no? https://hub.docker.com/repository/registry-1.docker.io/owasp/cwe-tool/tags?page=1&ordering=last_updated

**Pull request merged**
